### ISSUE TITLE
API call for Total Bytes used per Voucher?

### ISSUE THREAD

**Issue by seanmavley** [delian/node-unifiapi#2]
I've been going through the API calls and I can't find one where I specify the voucher code, and it gives me the total used per that voucher.

I'm asking because, users of my hotspot are always asking for how much data they've used. I wanna put together a simple Express app where they could enter their voucher, and have the amount used and amount left shown.

I'm loving this project of yours so much. Thanks.

**Comment by delian** [comment]
Generally, the only place I've seen accounting data is in the client list. Check list_clients()

**Comment by seanmavley** [comment]
I think the problem with using the `list_clients()` (https://github.com/delian/node-unifiapi#UnifiAPI+list_clients)  is that, it lists connected clients. However, the person checking voucher might not necessarily be connected to the APs

**Comment by delian** [comment]
It lists the clients that has been connected in a certain period of time.
So it includes some clients (depending on your configuration, lets say for
7 days) that are not currently connected


Delian
